test somthing i don't know

diff --git a/module3_task3/Makefile b/module3_task3/Makefile
--- a/module3_task3/Makefile
+++ b/module3_task3/Makefile
@@ -1,40 +1,48 @@
-# Variables
-BINARY_NAME := awesome-api
-LOG_FILE := $(BINARY_NAME).log
-PORT := 9999
+lint: ## lint
+	markdownlint -f DEPLOY.md README.md || true
 
+build: check ## Build awesome-api
+	go build -o awesome-api
+	hugo -d dist/
 
-help: ## Print a list of all the goals with descriptions
-	@awk 'BEGIN {FS = ":.*##"; } /^[a-zA-Z_-]+:.*?##/ { printf "  \033[36m%-10s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)
+run: ## Run awesome-api application
+	./awesome-api >./awesome-api.log 2>&1 &
 
-build: lint ## Build the binary
-	go build -o $(BINARY_NAME)
+stop: ## Stop awesome-api application
+	pkill awesome-api || true
 
-run: build ## Run the application
-	./$(BINARY_NAME) > $(LOG_FILE) 2>&1 &
+clean: ## Clean awesome-api application and log
+	pkill awesome-api || true
+	rm -f awesome-api awesome-api.log coverage-units.out coverage-integrations.out
+	rm -rf ./dist
+post: ## Create a new blog post
+	hugo new posts/$(POST_NAME).md
+	sed -i 's/title: .*/title: "$(POST_TITLE)"/' content/posts/$(POST_NAME).md
 
-stop: ## Stop the application
-	kill "$(shell pgrep $(BINARY_NAME))"
+test: ## Test current connection
+	make unit-tests
+	make integration-tests
 
-clean: ## Clean up generated files and artifacts
-	-kill "$(shell pgrep $(BINARY_NAME))"
-	rm -f $(BINARY_NAME)
-	rm -f $(LOG_FILE)
-	rm -f coverage-units.out coverage-integrations.out
-
-test:	## Test:
+unit-tests: ## Run tests to check for HelloHandler coverage
 	go test -v -short -coverprofile=coverage-units.out
-	go test -v -tags=integration -coverprofile=coverage-integrations.out ## Run both unit tests and integration tests
 
-lint: ## Perform static analysis on the source code
-	@golangci-lint run
+integration-tests: ## Run tests to check integrations coverage
+	go test -v -coverprofile=coverage-integrations.out
+check: ## Check markdown files
+	markdownlint ./content/posts/*.md
+	markdown-link-check ./content/posts/*.md
 
-unit-tests: ## Run unit tests
-	@go test -v -short -coverprofile=coverage-units.out
-	
-integration-tests: ##test
-	@go test -v -tags=integration -coverprofile=coverage-integrations.out ./...
+validate: ## Validate HTML  W3C Validator
+	make build
+	git clone https://github.com/holbertonschool/W3C-Validator.git
 
+package: ## Produce awesome-website.zip containing awesome-api and dist directory
+	zip -FSr awesome-website.zip . -i dist/ awesome-api
+	@if [ ! -f "awesome-website.zip" ]; then \
+		echo "Failed to generate awesome-website.zip"; \
+		exit 1; \
+	fi
 
-
-
+.SILENT:
+help: ## Display what each command does
+	cat Makefile | grep '##' | tr -d '##' | head -n -1
